spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    username: db-user
    password: your-password
    url: jdbc:postgresql://127.0.0.2:5432/postgres
    readUrl: jdbc:postgresql://127.0.0.3:5432/postgres
    readUrls: jdbc:postgresql://127.0.0.3:5432/postgres,jdbc:postgresql://127.0.0.4:5432/postgres,jdbc:postgresql://127.0.0.5:5432/postgres
